"""HDL generation tests for DFF reset support (Step 22): the 4 new
reset-aware shapes generated by app.domain.hdl.generator._dff_shape, and
confirmation that the pre-existing no-reset shape/Verilog is completely
unchanged.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest

from app.domain.hdl.generator import generate_verilog
from app.domain.ir.models import (
    Component,
    Connection,
    ConnectionEndpoint,
    CURRENT_SCHEMA_VERSION,
    IRDocument,
    Port,
    PortDirection,
    Provenance,
    ResetPolarity,
    ResetSpec,
    ResetTiming,
)

_CREATED_AT = datetime(2026, 9, 14, tzinfo=timezone.utc)


def _provenance() -> Provenance:
    return Provenance(source="manual", created_at=_CREATED_AT)


def _dff_document_with_reset(reset: ResetSpec | None) -> IRDocument:
    in_d = Component(
        id="in_d", kind="input", name="D_IN",
        ports=[Port(id="in_d.out", name="out", direction=PortDirection.OUTPUT, width=1)],
    )
    in_clk = Component(
        id="in_clk", kind="input", name="CLK_IN",
        ports=[Port(id="in_clk.out", name="out", direction=PortDirection.OUTPUT, width=1, type="clock")],
    )
    dff_ports = [
        Port(id="dff1.d", name="d", direction=PortDirection.INPUT, width=1),
        Port(id="dff1.clk", name="clk", direction=PortDirection.INPUT, width=1, type="clock"),
        Port(id="dff1.q", name="q", direction=PortDirection.OUTPUT, width=1),
    ]
    components = [in_d, in_clk]
    connections = [
        Connection(id="conn_d", source=ConnectionEndpoint(component_id="in_d", port_id="in_d.out"), target=ConnectionEndpoint(component_id="dff1", port_id="dff1.d")),
        Connection(id="conn_clk", source=ConnectionEndpoint(component_id="in_clk", port_id="in_clk.out"), target=ConnectionEndpoint(component_id="dff1", port_id="dff1.clk")),
    ]

    if reset is not None:
        in_reset = Component(
            id="in_reset", kind="input", name="RESET_IN",
            ports=[Port(id="in_reset.out", name="out", direction=PortDirection.OUTPUT, width=1)],
        )
        components.append(in_reset)
        dff_ports.append(Port(id="dff1.reset", name="reset", direction=PortDirection.INPUT, width=1))
        connections.append(
            Connection(id="conn_reset", source=ConnectionEndpoint(component_id="in_reset", port_id="in_reset.out"), target=ConnectionEndpoint(component_id="dff1", port_id="dff1.reset"))
        )

    dff1 = Component(id="dff1", kind="DFF", name="DFF1", ports=dff_ports, reset=reset)
    components.append(dff1)

    out_q = Component(
        id="out_q", kind="output", name="Q_OUT",
        ports=[Port(id="out_q.in", name="in", direction=PortDirection.INPUT, width=1)],
    )
    components.append(out_q)
    connections.append(
        Connection(id="conn_q", source=ConnectionEndpoint(component_id="dff1", port_id="dff1.q"), target=ConnectionEndpoint(component_id="out_q", port_id="out_q.in"))
    )

    return IRDocument(
        id="doc_dff_hdl_test",
        schema_version=CURRENT_SCHEMA_VERSION,
        design_version="1",
        name="DFF HDL Test",
        components=components,
        connections=connections,
        root_component_ids=[c.id for c in components],
        provenance=_provenance(),
    )


def test_no_reset_shape_name_and_verilog_are_unchanged() -> None:
    result = generate_verilog(_dff_document_with_reset(None))

    assert result.success is True
    assert result.module is not None
    assert "module _DFF_1W" in result.module.verilog
    assert "always @(posedge clk) q <= d;" in result.module.verilog
    assert "_DFF_1W_SYNC" not in result.module.verilog
    assert "_DFF_1W_ASYNC" not in result.module.verilog
    assert "reset" not in result.module.verilog.lower()


@pytest.mark.parametrize(
    ("polarity", "timing", "expected_shape", "expected_condition"),
    [
        (ResetPolarity.ACTIVE_HIGH, ResetTiming.SYNCHRONOUS, "_DFF_1W_SYNC_HIGH", "if (reset)"),
        (ResetPolarity.ACTIVE_LOW, ResetTiming.SYNCHRONOUS, "_DFF_1W_SYNC_LOW", "if (!reset)"),
        (ResetPolarity.ACTIVE_HIGH, ResetTiming.ASYNCHRONOUS, "_DFF_1W_ASYNC_HIGH", "if (reset)"),
        (ResetPolarity.ACTIVE_LOW, ResetTiming.ASYNCHRONOUS, "_DFF_1W_ASYNC_LOW", "if (!reset)"),
    ],
)
def test_all_four_reset_shapes_generate_correct_verilog(polarity, timing, expected_shape, expected_condition) -> None:
    reset_spec = ResetSpec(polarity=polarity, timing=timing)
    result = generate_verilog(_dff_document_with_reset(reset_spec))

    assert result.success is True
    assert result.module is not None
    verilog = result.module.verilog

    assert f"module {expected_shape}" in verilog
    assert expected_condition in verilog
    assert "q <= 1'b0" in verilog
    assert ".reset(" in verilog


def test_synchronous_reset_is_checked_inside_the_clocked_always_block() -> None:
    reset_spec = ResetSpec(polarity=ResetPolarity.ACTIVE_HIGH, timing=ResetTiming.SYNCHRONOUS)
    result = generate_verilog(_dff_document_with_reset(reset_spec))

    assert result.success is True
    verilog = result.module.verilog

    assert "always @(posedge clk) begin" in verilog
    assert "posedge reset" not in verilog
    assert "negedge reset" not in verilog


def test_asynchronous_reset_is_added_to_the_sensitivity_list() -> None:
    reset_spec = ResetSpec(polarity=ResetPolarity.ACTIVE_HIGH, timing=ResetTiming.ASYNCHRONOUS)
    result = generate_verilog(_dff_document_with_reset(reset_spec))

    assert result.success is True
    verilog = result.module.verilog

    assert "always @(posedge clk or posedge reset) begin" in verilog


def test_asynchronous_active_low_reset_uses_negedge_in_sensitivity_list() -> None:
    reset_spec = ResetSpec(polarity=ResetPolarity.ACTIVE_LOW, timing=ResetTiming.ASYNCHRONOUS)
    result = generate_verilog(_dff_document_with_reset(reset_spec))

    assert result.success is True
    verilog = result.module.verilog

    assert "always @(posedge clk or negedge reset) begin" in verilog
