import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1500, height: 1050 }, deviceScaleFactor: 1.3 });
await p.goto('http://localhost:3139', { waitUntil: 'networkidle' });
await p.waitForSelector('canvas', { timeout: 25000 });
await p.mouse.move(700,400); await p.mouse.down(); await p.mouse.move(730,395,{steps:5}); await p.mouse.up();
await p.waitForTimeout(2800);
await p.screenshot({ path: 'screenshots/B0-light.png' });
await p.getByRole('button', { name: /Switch to dark/ }).click();
await p.waitForTimeout(2200);
await p.screenshot({ path: 'screenshots/B0-dark.png' });
await b.close(); console.log('captured ok');
